#!/usr/bin/env python3

import hashlib
import json
from pathlib import Path


HELPER_ROOT = Path(__file__).resolve().parent.parent
PAYLOAD_ROOT = HELPER_ROOT / "Resources" / "tunnel-wheelhouse"
MANIFEST_PATH = PAYLOAD_ROOT / "runtime-manifest.json"
SWIFT_PATH = HELPER_ROOT / "GeneratedTunnelTrustAnchor.swift"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> None:
    wheel_paths = sorted(PAYLOAD_ROOT.glob("*.whl"))
    if not wheel_paths:
        raise SystemExit("tunnel-wheelhouse contains no wheels")
    unexpected = sorted(
        path.name
        for path in PAYLOAD_ROOT.iterdir()
        if path.is_file() and path.suffix != ".whl" and path != MANIFEST_PATH
    )
    if unexpected:
        raise SystemExit(f"unexpected payload files: {', '.join(unexpected)}")

    entries = [
        {
            "mode": 0o600,
            "relativePath": path.name,
            "sha256": sha256(path),
        }
        for path in wheel_paths
    ]
    manifest_data = json.dumps(
        {"files": entries},
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    MANIFEST_PATH.write_bytes(manifest_data)
    manifest_digest = hashlib.sha256(manifest_data).hexdigest()

    swift_entries = "\n".join(
        "        EmbeddedPayloadFile("
        f'relativePath: "{entry["relativePath"]}", '
        f'sha256: "{entry["sha256"]}", mode: 0o600'
        "),"
        for entry in entries
    )
    swift_source = f"""// Generated by Scripts/generate_tunnel_trust_anchor.py. Do not edit.

enum GeneratedTunnelTrustAnchor {{
    static let digestTable = EmbeddedDigestTable(
        manifestSHA256: "{manifest_digest}",
        files: [
{swift_entries}
        ],
        buildPlan: OfflineRuntimeBuildPlan(
            requirement: "pymobiledevice3==9.36.3",
            executableRelativePath: "runtime/pymobiledevice3"
        )
    )
}}
"""
    SWIFT_PATH.write_text(swift_source, encoding="utf-8")


if __name__ == "__main__":
    main()
