#!/usr/bin/env python3

import hashlib
import json
import re
from pathlib import Path


HELPER_ROOT = Path(__file__).resolve().parent.parent
PROJECT_ROOT = HELPER_ROOT.parent
LOCKFILE_PATH = (
    PROJECT_ROOT
    / "iPhoneLocationMove"
    / "Device"
    / "Resources"
    / "pymobiledevice3.lock"
)
PAYLOAD_ROOT = HELPER_ROOT / "Resources" / "tunnel-wheelhouse"
MANIFEST_PATH = PAYLOAD_ROOT / "runtime-manifest.json"
SWIFT_PATH = HELPER_ROOT / "GeneratedTunnelTrustAnchor.swift"
REQUIREMENT_PREFIX = "pymobiledevice3=="
WHEEL_NAME_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*\.whl$")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def fail(message: str) -> None:
    raise SystemExit(message)


def read_requirement() -> str:
    if LOCKFILE_PATH.is_symlink() or not LOCKFILE_PATH.is_file():
        fail(f"lockfile is missing: {LOCKFILE_PATH}")
    try:
        lines = [
            line.strip()
            for line in LOCKFILE_PATH.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    except (OSError, UnicodeError) as error:
        fail(f"unable to read lockfile: {error}")
    if len(lines) != 1 or not lines[0].startswith(REQUIREMENT_PREFIX):
        fail("lockfile must contain exactly one pinned pymobiledevice3 requirement")
    requirement = lines[0]
    version = requirement[len(REQUIREMENT_PREFIX) :]
    if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.!+_-]*", version):
        fail("lockfile requirement is not a valid pinned version")
    return requirement


def wheel_paths() -> list[Path]:
    if not PAYLOAD_ROOT.is_dir() or PAYLOAD_ROOT.is_symlink():
        fail(f"wheelhouse is missing: {PAYLOAD_ROOT}")
    entries = sorted(PAYLOAD_ROOT.iterdir(), key=lambda path: path.name)
    unexpected = [
        path.name
        for path in entries
        if path != MANIFEST_PATH
        and (
            not path.is_file()
            or path.is_symlink()
            or path.suffix != ".whl"
        )
    ]
    if unexpected:
        fail(f"unexpected wheelhouse payload: {', '.join(unexpected)}")
    wheels = [path for path in entries if path.suffix == ".whl"]
    if not wheels:
        fail("tunnel-wheelhouse contains no wheels")
    invalid_names = [
        path.name for path in wheels if not WHEEL_NAME_PATTERN.fullmatch(path.name)
    ]
    if invalid_names:
        fail(f"invalid wheel filenames: {', '.join(invalid_names)}")
    return wheels


def primary_wheel_path(wheels: list[Path], requirement: str) -> Path:
    package, version = requirement.split("==", 1)
    matches = []
    for path in wheels:
        parts = path.name[:-4].split("-")
        if len(parts) >= 2 and parts[0].replace("_", "-") == package:
            if parts[1] == version:
                matches.append(path)
    if len(matches) != 1:
        fail(
            "wheelhouse must contain exactly one primary wheel for "
            f"{requirement}"
        )
    return matches[0]


def manifest_bytes(wheels: list[Path]) -> bytes:
    entries = [
        {
            "mode": 0o600,
            "relativePath": path.name,
            "sha256": sha256(path),
        }
        for path in wheels
    ]
    return json.dumps(
        {"files": entries},
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


def swift_source(manifest_data: bytes, wheels: list[Path], requirement: str) -> str:
    manifest_digest = hashlib.sha256(manifest_data).hexdigest()
    swift_entries = "\n".join(
        "        EmbeddedPayloadFile("
        f'relativePath: "{path.name}", '
        f'sha256: "{sha256(path)}", mode: 0o600'
        "),"
        for path in wheels
    )
    return f"""// Generated by Scripts/generate_tunnel_trust_anchor.py. Do not edit.

enum GeneratedTunnelTrustAnchor {{
    static let digestTable = EmbeddedDigestTable(
        manifestSHA256: "{manifest_digest}",
        files: [
{swift_entries}
        ],
        buildPlan: OfflineRuntimeBuildPlan(
            requirement: TunnelRuntimePin.requirement,
            executableRelativePath: "runtime/pymobiledevice3"
        )
    )
}}
"""


def main() -> None:
    requirement = read_requirement()
    wheels = wheel_paths()
    primary_wheel_path(wheels, requirement)
    manifest_data = manifest_bytes(wheels)
    if MANIFEST_PATH.is_symlink():
        fail("runtime-manifest.json is not a regular file")
    if MANIFEST_PATH.exists():
        if not MANIFEST_PATH.is_file():
            fail("runtime-manifest.json is not a regular file")
        try:
            existing_manifest = MANIFEST_PATH.read_bytes()
        except OSError as error:
            fail(f"unable to read runtime-manifest.json: {error}")
        if existing_manifest != manifest_data:
            fail("runtime-manifest.json does not match generated wheel digests")
    else:
        try:
            MANIFEST_PATH.write_bytes(manifest_data)
        except OSError as error:
            fail(f"unable to write runtime-manifest.json: {error}")

    try:
        SWIFT_PATH.write_text(
            swift_source(manifest_data, wheels, requirement),
            encoding="utf-8",
        )
    except OSError as error:
        fail(f"unable to write GeneratedTunnelTrustAnchor.swift: {error}")


if __name__ == "__main__":
    main()
